runtime: php
env: flex

runtime_config:
  document_root: web
  front_controller_file: mod_rewrite.php

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_IP: 35.202.97.67
  MYSQL_USER: root
  MYSQL_PASSWORD: 2June1989!
  MYSQL_DBNAME: community
